

const url = 'https://coinmarketcap.com/'


/**
 * @dev Testing to figure out optimal action sequence
 */

  .goto(url)
  .click('a[href="/currencies/bitcoin/"')

  // .click('#sc-1ejyco6-0 gQqumm')
  /**
   * @dev Since left starts on November, first 11 clicks, then 12 * 7 clicks
   */
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous') // 11 to get to December 2019
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('sc-1ejyco6-0 czBWYA') // Click "Done"
  // .end().then(console.log)
  .catch(error => {
    console.log("Couldn't click because: ", error)
  })


/**
 * @dev Granular approach to add intermediate actions and functions
const goToPage = nightmare.goto(url)
// how to wait on a page
const waitOnPage = goToPage.wait(2000)

const closePage = waitOnPage.end().then(console.log)
  .catch(error => {
    console.error('Search failed:', error)
  })

closePage
*/