const puppeteer = require('puppeteer')


const url = 'https://coinmarketcap.com/'; // this semi-colon is needed

/**
 * @dev Testing to figure out optimal action sequence
 */
(async () => {
  const browser = await puppeteer.launch({ headless: false })
  const page = await browser.newPage()
  await page.goto('https://coinmarketcap.com/')
  // await page.screenshot({ path: './example.png' })
  await browser.close()

  .click('a[href="/currencies/bitcoin/"')
  // await browser.close()
})();


/**
  // .click('#sc-1ejyco6-0 gQqumm')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous') // 11 to get to December 2019
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('react-datepicker__navigation react-datepicker__navigation--previous')
  .click('sc-1ejyco6-0 czBWYA') // Click "Done"
  // .end().then(console.log)
  .catch(error => {
    console.log("Couldn't click because: ", error)
  })
*/

/**
 * @dev Granular approach to add intermediate actions and functions
const goToPage = nightmare.goto(url)
// how to wait on a page
const waitOnPage = goToPage.wait(2000)

const closePage = waitOnPage.end().then(console.log)
  .catch(error => {
    console.error('Search failed:', error)
  })

closePage
*/